/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import DAO.ControleDAO;
import Model.Entreprise;
import Model.Personne;
import Model.Visite;
import java.awt.Color;
import java.awt.Font;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *Date du programme
 *      30/05/2023
 * Objet du programme
 *      Frame du formulaire d'enregistrement des visiteurs
 * @author Jules Turpin
 */

public class Frm_FormulaireEnregistrement extends javax.swing.JFrame {

    /**
     * Creates new form Frm_FormulaireEnregistrement
     */
    public Frm_FormulaireEnregistrement() {
        initComponents();
        
        //Forçage du pleine écran
        this.setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
        //Désactivation de la modification de taille de l'application
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        //Couleur du background
        this.getContentPane().setBackground(Color.WHITE);
                
        //Mise en place de l'image
        ImageIcon iconLogoPDiamond = new ImageIcon("C:\\Images\\Logo\\LOGO_D_petit.png");
        ImageIcon iconLogoLichtgitter = new ImageIcon("C:\\Images\\Logo\\LOGO_LG.png");
        jLogoDiamondPBA.setIcon(iconLogoPDiamond);
        jLogoLichtgitterA.setIcon(iconLogoLichtgitter);
        
        jPanelVisite.setBackground(Color.WHITE);
        jPanelInfoEntreprise.setBackground(Color.WHITE);
        jPanelVosInfos.setBackground(Color.WHITE);
        
        jPanel1.setBackground(Color.WHITE);
        jPanel4.setBackground(Color.WHITE);
        jPanel5.setBackground(Color.WHITE);
        jPanel6.setBackground(Color.WHITE);
        
        jPanel7.setBackground(Color.WHITE);
        jPanel8.setBackground(Color.WHITE);
        
        jPanelPvisite.setBackground(Color.WHITE);
        
        checkboxParticulier.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
    }
    
    /** g
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPanelVisite = new javax.swing.JPanel();
        jLabelVisite = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jButtonAbandon = new javax.swing.JButton();
        jPanelPvisite = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelMessageErreur = new javax.swing.JLabel();
        jLabelVisiteur = new javax.swing.JLabel();
        jPanelVosInfos = new javax.swing.JPanel();
        jLabelVosInfos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelVinfoNom = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelEtoile1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelVinfoMail = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabelVinfoPrenom = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabelEtoile3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelVinfoTel = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanelInfoEntreprise = new javax.swing.JPanel();
        jLabelInfoEntreprise = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelEnom = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabelEactivite = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        checkboxParticulier = new java.awt.Checkbox();
        jPiedPageA = new javax.swing.JPanel();
        jPied1A = new javax.swing.JPanel();
        jLogoDiamondPBA = new javax.swing.JLabel();
        jLogoLichtgitterA = new javax.swing.JLabel();
        jTextPiedP1A = new javax.swing.JLabel();
        AjTextpiedP2A = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPied2A = new javax.swing.JPanel();
        jTextPied3A = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabelVisite.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelVisite.setText("Visite :");

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonAbandon.setText("Abandonner");
        jButtonAbandon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbandonActionPerformed(evt);
            }
        });

        jLabel10.setText("Personne Visitée :");

        javax.swing.GroupLayout jPanelPvisiteLayout = new javax.swing.GroupLayout(jPanelPvisite);
        jPanelPvisite.setLayout(jPanelPvisiteLayout);
        jPanelPvisiteLayout.setHorizontalGroup(
            jPanelPvisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPvisiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPvisiteLayout.setVerticalGroup(
            jPanelPvisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPvisiteLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelPvisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessageErreur)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessageErreur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelVisiteLayout = new javax.swing.GroupLayout(jPanelVisite);
        jPanelVisite.setLayout(jPanelVisiteLayout);
        jPanelVisiteLayout.setHorizontalGroup(
            jPanelVisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPvisite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisite)
                    .addGroup(jPanelVisiteLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAbandon))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelVisiteLayout.setVerticalGroup(
            jPanelVisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVisite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPvisite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelVisiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVisiteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVisiteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButtonAbandon)
                .addContainerGap())
        );

        jLabelVisiteur.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelVisiteur.setText("Visite");

        jLabelVosInfos.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabelVosInfos.setText("Vos informations :");

        jLabelVinfoNom.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelVinfoNom.setText("Nom :");

        jLabelEtoile1.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVinfoNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtoile1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVinfoNom)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEtoile1))
                .addContainerGap())
        );

        jLabelVinfoMail.setText("Mail :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVinfoMail)
                .addGap(18, 18, 18)
                .addComponent(jTextField4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVinfoMail)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelVinfoPrenom.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelVinfoPrenom.setText("Prénom :");

        jLabelEtoile3.setText("*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVinfoPrenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtoile3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVinfoPrenom)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEtoile3))
                .addContainerGap())
        );

        jLabelVinfoTel.setText("Tél. :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVinfoTel)
                .addGap(18, 18, 18)
                .addComponent(jTextField6)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVinfoTel)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelVosInfosLayout = new javax.swing.GroupLayout(jPanelVosInfos);
        jPanelVosInfos.setLayout(jPanelVosInfosLayout);
        jPanelVosInfosLayout.setHorizontalGroup(
            jPanelVosInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVosInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVosInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVosInfosLayout.createSequentialGroup()
                        .addComponent(jLabelVosInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302))
                    .addGroup(jPanelVosInfosLayout.createSequentialGroup()
                        .addGroup(jPanelVosInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelVosInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanelVosInfosLayout.setVerticalGroup(
            jPanelVosInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVosInfosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelVosInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelVosInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVosInfosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVosInfosLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelInfoEntreprise.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelInfoEntreprise.setText("Informations sur votre entreprise :");

        jLabelEnom.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelEnom.setText("Nom :");

        jLabel8.setText("*");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEnom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnom)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelEactivite.setText("Activité :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEactivite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEactivite)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkboxParticulier.setForeground(new java.awt.Color(0, 0, 0));
        checkboxParticulier.setLabel("Je suis un particulier ");
        checkboxParticulier.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxParticulierItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEntrepriseLayout = new javax.swing.GroupLayout(jPanelInfoEntreprise);
        jPanelInfoEntreprise.setLayout(jPanelInfoEntrepriseLayout);
        jPanelInfoEntrepriseLayout.setHorizontalGroup(
            jPanelInfoEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEntrepriseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoEntrepriseLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoEntrepriseLayout.createSequentialGroup()
                        .addGroup(jPanelInfoEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfoEntreprise)
                            .addComponent(checkboxParticulier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInfoEntrepriseLayout.setVerticalGroup(
            jPanelInfoEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEntrepriseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInfoEntreprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoEntrepriseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(checkboxParticulier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPiedPageA.setBackground(new java.awt.Color(255, 255, 255));
        jPiedPageA.setPreferredSize(new java.awt.Dimension(768, 108));

        jPied1A.setBackground(new java.awt.Color(60, 59, 58));

        jTextPiedP1A.setForeground(new java.awt.Color(255, 255, 255));
        jTextPiedP1A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTextPiedP1A.setText("Le Caillebotis Diamond est une société du groupe Lichtgitter, un des leaders mondiaux sur le");

        AjTextpiedP2A.setForeground(new java.awt.Color(255, 255, 255));
        AjTextpiedP2A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AjTextpiedP2A.setText("le monde");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("marché du caillebotis avec plus de 15 filiales en Europe & de nombreuses repésentations dans");

        javax.swing.GroupLayout jPied1ALayout = new javax.swing.GroupLayout(jPied1A);
        jPied1A.setLayout(jPied1ALayout);
        jPied1ALayout.setHorizontalGroup(
            jPied1ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPied1ALayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLogoDiamondPBA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPied1ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AjTextpiedP2A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextPiedP1A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLogoLichtgitterA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPied1ALayout.setVerticalGroup(
            jPied1ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPied1ALayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPied1ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLogoDiamondPBA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPied1ALayout.createSequentialGroup()
                        .addComponent(jTextPiedP1A)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(AjTextpiedP2A))
                    .addComponent(jLogoLichtgitterA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPied2A.setBackground(new java.awt.Color(249, 77, 30));

        jTextPied3A.setText(" @ 2023 Le Caillebotis Diamond");

        javax.swing.GroupLayout jPied2ALayout = new javax.swing.GroupLayout(jPied2A);
        jPied2A.setLayout(jPied2ALayout);
        jPied2ALayout.setHorizontalGroup(
            jPied2ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPied2ALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextPied3A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPied2ALayout.setVerticalGroup(
            jPied2ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPied2ALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextPied3A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPiedPageALayout = new javax.swing.GroupLayout(jPiedPageA);
        jPiedPageA.setLayout(jPiedPageALayout);
        jPiedPageALayout.setHorizontalGroup(
            jPiedPageALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPied1A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPied2A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPiedPageALayout.setVerticalGroup(
            jPiedPageALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPiedPageALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPied1A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPied2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabelVisiteur)
                .addGap(326, 326, 326))
            .addComponent(jPiedPageA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVisite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelInfoEntreprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelVosInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVisiteur)
                .addGap(63, 63, 63)
                .addComponent(jPanelVosInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInfoEntreprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVisite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(jPiedPageA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Méthode permettant le contrôler la validiter du mail (Regex)
    public static boolean mailPatternMatches(String personneMail, String regexPattern){
        return Pattern.compile(regexPattern).matcher(personneMail).matches();
    }
    
    //Vérification et Envoie de toute les données récupérer vers ControleDAO pour l'insertion + Impression du Badge de visite
    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        
        //récupération des champs de saisis
        //champs de saisis de personne        
        String personneNom = jTextField1.getText().toUpperCase();
        String personnePrenom = jTextField5.getText();
        String personneMail = jTextField4.getText();
        String personneTel = jTextField6.getText();
                
        //champs de saisis de entreprise
        String entrepriseNom = jTextField8.getText().toUpperCase();
        String entrepriseActivite = jTextField9.getText();
        
        //champs de saisis de visite
        String visitePVisite = jTextField10.getText(); 
        
        //création des instance de uneEntreprise, unePersonne et uneVisite
        //Entreprise = null si case particulier cocher  
        Entreprise uneEntreprise = null;
        Personne unePersonne = new Personne();
        Visite uneVisite = new Visite();
        
        boolean verifCheckBox = checkboxParticulier.getState();
        boolean verifInsertion = true; 
        boolean mailRegexTest;
        boolean verifContenuMail = true;
        boolean verifPNom = true;
        boolean verifPPrenom = true;
        boolean verifENom = true;
        
        int countVerif = 0;
       
        //contrôle de saisie de la zone de text nom du visiteur
        if(personneNom.equals("")){
            
            jLabelVinfoNom.setForeground(new Color(227,108,10));
            jLabelVinfoNom.setFont(new Font("Segoe UI", Font.BOLD, 15));
            verifInsertion = false;
            verifPNom = false;
            countVerif ++;
        } else {
            jLabelVinfoNom.setForeground(new Color(60,63, 65));
        }
        
        //contrôle de saisie de la zone de text prenom du visiteur
        if(personnePrenom.equals("")){
            
            jLabelVinfoPrenom.setForeground(new Color(227, 108, 10));
            jLabelVinfoPrenom.setFont(new Font("Segoe UI", Font.BOLD, 15));
            verifInsertion = false;
            verifPPrenom = false;
            countVerif ++;
        } else {
            jLabelVinfoPrenom.setForeground(new Color(60,63, 65));
        }
        
        //contrôle de saisie de la zone de text Nom de l'entreprise
        if(verifCheckBox == false){
            
            if(entrepriseNom.equals("")){
            jLabelEnom.setForeground(new Color(227, 108, 10));
            jLabelEnom.setFont(new Font("Segoe UI", Font.BOLD, 15));
            verifInsertion = false;
            verifENom = false;
            countVerif ++;
            } else {
                jLabelEnom.setForeground(new Color(60,63, 65));
            }
        }
        
        //contrôle du mail si il est saisie (@ + contenu avant et après le @)
        if(personneMail.equals("")){

        } else {
            
            String regexPattern = "^(.+)@(\\S+)$"; //vérification uniquement de l'écriture du @ + si caractère avant et après celui-ci / changer ce code : "^(.+)@(\\S+)$" pour une vérification plus pousser
            mailRegexTest = mailPatternMatches(personneMail, regexPattern);
            
            if(mailRegexTest == false){
                verifInsertion = false; 
                jLabelVinfoMail.setForeground(new Color(227, 108, 10));
                jLabelVinfoMail.setFont(new Font("Segoe UI", Font.BOLD, 15));
                verifContenuMail = false;
                countVerif ++;
            } else {
                jLabelVinfoMail.setForeground(new Color(60,63, 65));
            }
        }
        
        //Affichage des erreurs
        if(countVerif == 0){
            jLabelMessageErreur.setText("Aucun erreur");
        } else if(countVerif == 1){
            if(verifPNom == false){
                jLabelMessageErreur.setText("Votre nom est manquant");
            } else if(verifPPrenom == false){
                jLabelMessageErreur.setText("Votre Prénom est manquant");
            } else if(verifENom == false){
                jLabelMessageErreur.setText("Le nom de votre entreprise est manquant");
            } else if(verifContenuMail == false){
                jLabelMessageErreur.setText("Votre adresse e-mail n'est pas valide");
            }
        } else if(countVerif >= 2 && verifContenuMail == false){
            jLabelMessageErreur.setText("Plusieurs champs sont manquant et l'adresse e-mail n'est pas valide");
        } else {
            jLabelMessageErreur.setText("Plusieurs champs sont manquant");
        }
        
        
        //si toute les champs obligatoire on été remplie (+ si le champ mail a été remplie et est valide) : 
        //liaison des informations saisie + envoie des informations vers controleInsertion pour contrôler et insérer les informations sur la base de données
        if(verifInsertion != false){

            if(verifCheckBox == false){

                uneEntreprise = new Entreprise();

                uneEntreprise.setENT_NOM(entrepriseNom);
                uneEntreprise.setENT_ACTIVITE(entrepriseActivite);
            }

            //Liaison des données
            unePersonne.setPER_NOM(personneNom);
            unePersonne.setPER_PRENOM(personnePrenom);
            unePersonne.setPER_MAIL(personneMail);
            unePersonne.setPER_TEL(personneTel);

            uneVisite.setVIS_PVISITE(visitePVisite);

            int controleFormulaire = ControleDAO.controleInsertion(uneEntreprise, unePersonne, uneVisite);
            
            //Impression du badge
            Frm_BadgeImpression badgeImpression = new Frm_BadgeImpression();
            badgeImpression.printFrame();  
            
            //pop-up
            JOptionPane.showMessageDialog(this, "Votre enregistrement a bien été validé, votre badge est en cours d'édition !\r\n Merci de scanner votre badge lors de votre départ");
            
            //Retour à l'accueil
            Frm_Accueil Accueil = new Frm_Accueil();
            Accueil.setVisible(true);
            this.dispose();
        }   
    }//GEN-LAST:event_jButtonValiderActionPerformed

    //Abandon d'un enregistrement retour à l'accueil
    private void jButtonAbandonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbandonActionPerformed
        // TODO add your handling code here:
        JFrame leFormulaire = new JFrame();
        
        leFormulaire = new Frm_Accueil();
        leFormulaire.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAbandonActionPerformed

    //Si CheckBox particulier cocher blocage des cases Nom et Activité de l'entreprise
    private void checkboxParticulierItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxParticulierItemStateChanged
        // TODO add your handling code here:
        
        //Empêchement de la saisie dans entreprise nom et activite si la checkbox "je suis un particulier" est cocher
        if (checkboxParticulier.getState()){
            jTextField8.setEnabled(false);
            jTextField9.setEnabled(false);
        } else {
            jTextField8.setEnabled(true);
            jTextField9.setEnabled(true);
        }
    }//GEN-LAST:event_checkboxParticulierItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_FormulaireEnregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_FormulaireEnregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_FormulaireEnregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_FormulaireEnregistrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_FormulaireEnregistrement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AjTextpiedP2A;
    private java.awt.Checkbox checkboxParticulier;
    private javax.swing.JButton jButtonAbandon;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEactivite;
    private javax.swing.JLabel jLabelEnom;
    private javax.swing.JLabel jLabelEtoile1;
    private javax.swing.JLabel jLabelEtoile3;
    private javax.swing.JLabel jLabelInfoEntreprise;
    private javax.swing.JLabel jLabelMessageErreur;
    private javax.swing.JLabel jLabelVinfoMail;
    private javax.swing.JLabel jLabelVinfoNom;
    private javax.swing.JLabel jLabelVinfoPrenom;
    private javax.swing.JLabel jLabelVinfoTel;
    private javax.swing.JLabel jLabelVisite;
    private javax.swing.JLabel jLabelVisiteur;
    private javax.swing.JLabel jLabelVosInfos;
    private javax.swing.JLabel jLogoDiamondPBA;
    private javax.swing.JLabel jLogoLichtgitterA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelInfoEntreprise;
    private javax.swing.JPanel jPanelPvisite;
    private javax.swing.JPanel jPanelVisite;
    private javax.swing.JPanel jPanelVosInfos;
    private javax.swing.JPanel jPied1A;
    private javax.swing.JPanel jPied2A;
    private javax.swing.JPanel jPiedPageA;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel jTextPied3A;
    private javax.swing.JLabel jTextPiedP1A;
    // End of variables declaration//GEN-END:variables

}